
FFTW.js:
	emcc -O3 \
	     --memory-init-file 0 \
	     -s NO_FILESYSTEM=1 \
	     -s MODULARIZE=1 \
	     -s PRECISE_F32=1 \
	     -s EXPORT_NAME="'FFTWModule'" \
	     -s LINKABLE=1 \
	     -s EXPORT_ALL=1 \
	     -s ASSERTIONS=1 \
	     -o FFTW.js \
	     fftw-3.3.4/.libs/libfftw3f.a

clean:
	rm -f FFTW.js

